service: notes-nia  
runtime: nodejs20
env: standard
instance_class: F1

handlers:
  # Mengarahkan root ke index.html
  - url: /
    static_files: index.html
    upload: index.html

  # Mengizinkan akses ke semua file statis lainnya (JS, CSS, Gambar)
  - url: /(.*)
    static_files: \1
    upload: (.*)