steps:
  # Step 1: Build Docker Image untuk Frontend
  # Namanya disesuaikan jadi notes-fe-nia biar rapi
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/notes-fe-nia', './frontend']

  # Step 2: Push Image ke Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notes-fe-nia']

  # Step 3: Deploy ke App Engine (Skenario 2)
  # Ini yang bakal bikin FE kamu jalan di App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', 'frontend/app.yaml']